from scapy.all import sniff, IP, TCP, UDP, ICMP, conf
from datetime import datetime

# ============================================================
# Npcap Configuration
# ============================================================

conf.use_pcap = True

# Your Wi-Fi Npcap interface
WIFI_INTERFACE = r"\Device\NPF_{07B90B12-7BF3-4232-A47D-7D8F2565D05C}"

# ============================================================
# Packet Filter
# ============================================================

# Capture ONLY ICMP packets involving 8.8.8.8
# This is the traffic generated by:
# ping 8.8.8.8

PACKET_FILTER = "icmp and host 8.8.8.8"

# ============================================================
# Packet Counter
# ============================================================

packet_count = 0


# ============================================================
# Process Captured Packet
# ============================================================

def process_packet(packet):
    global packet_count

    packet_count += 1

    print("\n" + "=" * 60)

    print(f"Packet Number : {packet_count}")

    print(
        f"Time          : "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    # --------------------------------------------------------
    # IP Packet
    # --------------------------------------------------------

    if packet.haslayer(IP):

        source_ip = packet[IP].src
        destination_ip = packet[IP].dst

        print(f"Source IP     : {source_ip}")
        print(f"Destination IP: {destination_ip}")

        # ----------------------------------------------------
        # ICMP
        # ----------------------------------------------------

        if packet.haslayer(ICMP):

            print("Protocol      : ICMP")

            # ICMP type
            icmp_type = packet[ICMP].type

            if icmp_type == 8:
                print("ICMP Type     : Echo Request")

            elif icmp_type == 0:
                print("ICMP Type     : Echo Reply")

            else:
                print(f"ICMP Type     : {icmp_type}")

        # ----------------------------------------------------
        # TCP
        # ----------------------------------------------------

        elif packet.haslayer(TCP):

            source_port = packet[TCP].sport
            destination_port = packet[TCP].dport
            flags = packet[TCP].flags

            print("Protocol      : TCP")
            print(f"Source Port   : {source_port}")
            print(f"Destination Port: {destination_port}")
            print(f"TCP Flags     : {flags}")

        # ----------------------------------------------------
        # UDP
        # ----------------------------------------------------

        elif packet.haslayer(UDP):

            source_port = packet[UDP].sport
            destination_port = packet[UDP].dport

            print("Protocol      : UDP")
            print(f"Source Port   : {source_port}")
            print(f"Destination Port: {destination_port}")

        else:

            print("Protocol      : Other IP")

    else:

        print("Non-IP packet")

    print("=" * 60)


# ============================================================
# Start Packet Sniffer
# ============================================================

def start_sniffer():

    print("\n")
    print("=" * 60)
    print("       NETWORK IDS - PACKET SNIFFER")
    print("=" * 60)

    print("Starting packet capture...")
    print("Press CTRL+C to stop.")

    print("=" * 60)

    print(f"Interface : {WIFI_INTERFACE}")

    print("Using Wi-Fi adapter.")

    print("=" * 60)

    print(f"Filter    : {PACKET_FILTER}")

    print("Only ICMP traffic involving 8.8.8.8 will be captured.")

    print("=" * 60)

    try:

        sniff(
            iface=WIFI_INTERFACE,
            filter=PACKET_FILTER,
            prn=process_packet,
            store=False
        )

    except KeyboardInterrupt:

        print("\n")
        print("=" * 60)
        print("Packet capture stopped.")
        print(f"Total packets captured: {packet_count}")
        print("=" * 60)

    except Exception as e:

        print("\n")
        print("=" * 60)
        print("ERROR: Packet capture failed")
        print("=" * 60)

        print(e)

        print("=" * 60)


# ============================================================
# Main
# ============================================================

if __name__ == "__main__":
    start_sniffer()